---
abstract: 'Perl interface to the Virtual Terminal Emulation library'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::Depends: 0.20
  ExtUtils::MakeMaker: 0
  ExtUtils::PkgConfig: 1.03
  Glib: 1.01
  Gtk2: 1.00
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gnome2-Vte
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::Depends: 0.20
  ExtUtils::PkgConfig: 1.03
  Glib: 1.01
  Gtk2: 1.00
version: 0.10
